# Python Fundametals 

## https://swcarpentry.github.io/python-novice-inflammation/02-numpy.html

In [13]:
weight_kg = 60
print("weight in kg is ", weight_kg)
weight_lb = 2.2 * weight_kg
print("weight in lb is ", weight_lb)

weight in kg is  60
weight in lb is  132.0


In [15]:
patient_id = '001' 
print(patient_id) 

001


In [18]:
weight_lb = 'inflam_' + patient_id
print(weight_lb)

print(patient_id, 'weight in kilogram is' , 

inflam_001


In [23]:
print(type(60.4))
print(type(patient_id))

<class 'float'>
<class 'str'>


In [24]:
print('weight in pounds', 2.2 * weight_kg)

weight in pounds 132.0


In [25]:
weight_kg = 65.0
print('weight in kilograms is now:', weight_kg)

weight in kilograms is now: 65.0


In [26]:
# there are 2.2 pounds per kilogram. 

weight_lb = 2.2 * weight_kg 

print('weight in kilograms:' , weight_kg, 'and in pounds', weight_lb)

weight in kilograms: 65.0 and in pounds 143.0


In [28]:

weight_kg = 100
weight_lb = 2.2 * weight_kg
print('weight in kilograms:' , weight_kg, 'and in pounds', weight_lb)

weight in kilograms: 100 and in pounds 220.00000000000003


In [29]:
# Challenge 
mass = 47.5
print(mass) 
age = 122
print(age) 
mass = mass* 2.0 
print (mass) 
age = age - 20 
print (age) 

47.5
122
95.0
102


In [30]:
first, second = 'Grace', ' Hopper' 
third, fourth = second, first 
print(third, fourth)
#Hopper Grace

 Hopper Grace


In [31]:
# Data types 
planet = 'Earth' 
apple = 5
distance = 10.5 

print(type(planet))
print(type(apple))
print(type(distance))

#string, #int # float 

<class 'str'>
<class 'int'>
<class 'float'>


# Analyzing Patient Data 

## Loading Data into Python

In [33]:
import numpy 

In [39]:
#make sure your file is in the same folder where your code is. if its not then specify the directory as well. 
data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

print(data)


[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [40]:
print(type(data))


<class 'numpy.ndarray'>


In [41]:
#The type function will only tell you that a variable is a NumPy array but won’t tell you the type of thing inside the array. We can find out the type of the data contained in the NumPy array.
print(data.dtype) 

float64


In [42]:
print(data.shape) 

(60, 40)


In [46]:
print('first value in data :', data[0,0])

first value in data : 0.0


In [51]:
print('value in data :', data[0,5])

value in data : 2.0


### Slicing data


In [53]:
# Slide the data of the first 4 rows and 10 columns
# In python range the start index is included and the last index in excluded. 

print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [64]:
print (data[5:10, 0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


In [63]:
# [:3] means 0:3 and [3:] means from index 3 till end. 
small = data [:3, 36:]
# this means from 0:3 and column 36 to the end.
print ('small is:')
print (small) 


small is:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [62]:
numbers = [10, 20, 30, 40, 50]
numbers[:3]

[10, 20, 30]

## Analyzing Data

In [65]:
print(numpy.mean(data))


6.14875


In [66]:
import time 
print(time.ctime())

Mon Jul 27 10:51:00 2026


In [69]:
maxval, minval, stdval = numpy.max(data), numpy.min(data), numpy.std(data)

print("maximum inflammation is: ", maxval)
print('minimum inflammation is: ', minval)
print('standard deviation in inflammation is:', stdval)

maximum inflammation is:  20.0
minimum inflammation is:  0.0
standard deviation in inflammation is: 4.613833197118566


In [70]:
# taking the mean of patient 0 inflammation
patient_0 = data[0, :] 
numpy.mean(patient_0)

np.float64(5.45)

In [71]:
numpy.max(patient_0)

np.float64(18.0)

In [72]:
print('The maximum inflammation patient 0 is:',numpy.max(patient_0)) 

The maximum inflammation patient 0 is: 18.0


In [73]:
patient_1 = data[1, :] 

In [74]:
# Patient 1 data 
print('The maximum inflammation of patient 1 is : ', numpy.max(patient_1)) 

The maximum inflammation of patient 1 is :  18.0


In [75]:
# patient 2 without assigning it to a variable. 
print('the maximum inflammation of patient :', numpy.max(data[2,:]))

the maximum inflammation of patient : 19.0


### Analysis across the column and rows. 
- axis function is used. 
- axis = 0 is rows
- axis = 1 is columns
- axis = 0 means collaps all the columns into one row - that means it will give us the mean of all the column in one row.
- axis = 1 means collaps all the rows into one column and give me the mean of all the rows in one column.
- axis is actually a dimension and not rows and columns.
- numpy.mean(data, axis=0)
- you're telling NumPy:

    Collapse dimension 0 (the rows) - means give me the mean of the columns. 
    Now we will have only one value per column. 

- axis=1
- numpy.mean(data, axis=1)

- means

- Collapse dimension 1 (the columns).
- Now the columsn will dissapear and we are left with one value per row. 

In [77]:
print (numpy.max(data, axis = 1))
#axis = 1 means columns will dissapear and we will get one max value per row. 

[18. 18. 19. 17. 17. 18. 17. 20. 17. 18. 18. 18. 17. 16. 17. 18. 19. 19.
 17. 19. 19. 16. 17. 15. 17. 17. 18. 17. 20. 17. 16. 19. 15. 15. 19. 17.
 16. 17. 19. 16. 18. 19. 16. 19. 18. 16. 19. 15. 16. 18. 14. 20. 17. 15.
 17. 16. 17. 19. 18. 18.]


In [78]:
print (numpy.max(data, axis = 0))
#axis=0 means all the rows will be diminished to 1. it means will be get max value of each column. 

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 19. 18. 17. 16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  5.
  4.  3.  2.  1.]


In [79]:
print(numpy.max(data, axis=1).shape)

(60,)


In [80]:
print(numpy.max(data, axis=0).shape)

(40,)


In [81]:
print(numpy.mean(data, axis=1))

[5.45  5.425 6.1   5.9   5.55  6.225 5.975 6.65  6.625 6.525 6.775 5.8
 6.225 5.75  5.225 6.3   6.55  5.7   5.85  6.55  5.775 5.825 6.175 6.1
 5.8   6.425 6.05  6.025 6.175 6.55  6.175 6.35  6.725 6.125 7.075 5.725
 5.925 6.15  6.075 5.75  5.975 5.725 6.3   5.9   6.75  5.925 7.225 6.15
 5.95  6.275 5.7   6.1   6.825 5.975 6.725 5.7   6.25  6.4   7.05  5.9  ]


In [82]:
# Challange 

element = 'oxygen' 
print('first three character:' , element[0:3])
print('last three character:', element[3:])


first three character: oxy
last three character: gen


In [83]:
element[:4]
#oxyg

'oxyg'

In [84]:
element[4:]
#en

'en'

In [86]:
element[:]
#start : (to)  end - so it will oxygen. 

'oxygen'

In [87]:
element[-1]

'n'

In [88]:
element[-2]
#e

'e'

In [89]:
element[1:-1]
#xyge

'xyge'

In [90]:
element[-3:]

'gen'

In [91]:
element = 'carpentry'

In [92]:
element[-3:]

'try'

In [93]:
element = 'clone'

In [94]:
element[-3:]

'one'

In [95]:
element = 'hi' 

In [96]:
element[-3:]

'hi'

In [97]:
data [3:3, 4:4] 

array([], shape=(0, 0), dtype=float64)

In [98]:
data [3:3, :]

array([], shape=(0, 40), dtype=float64)

## Stacking Array 

In [99]:
A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print ('A = ')
print (A) 

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [100]:
B = numpy.hstack([A, A])
print ('B = ' )
print (B) 

B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


In [101]:
C = numpy.vstack([A, A])
print('C = ')
print(C)

C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


### Deleting a column or row 

- numpy.delete()


- The syntax is:

        numpy.delete(arr, obj, axis)
        arr → the array you want to modify
        obj → the index of the element(s) you want to remove
        axis → tells NumPy whether you are removing rows or columns

In [110]:
#Write some additional code that slices the first and last columns of A, and stacks them into a 3x2 array. Make sure to print the results to verify your solution.
D = numpy.hstack((A[:, :1], A[:, -1:]))
print ('D = ') 
print(D)

D = 
[[1 3]
 [4 6]
 [7 9]]


In [114]:
D = numpy.delete(arr=A, obj=1, axis=1)
print('D = ')
print(D)

# it will remove the column index 1, axis = 1 indicates column. 

D = 
[[1 3]
 [4 6]
 [7 9]]


In [113]:
D = numpy.delete(arr=A, obj=1, axis=0)
print('D = ')
print(D)

# want to remove the middle row - second row. 

D = 
[[1 2 3]
 [7 8 9]]


In [115]:
#Challenge 

# taking patient 3 week 1 data. 
patient_3_week1 = data[3, :7]
print(patient_3_week1)

[0. 0. 2. 0. 4. 2. 2.]


In [116]:
#differnce in successive values. 

numpy.diff(patient_3_week1)

array([ 0.,  2., -2.,  4., -2.,  0.])

In [117]:
#which axis 

numpy.diff(data, axis =1) 
#by rows. 

array([[ 0.,  1.,  2., ...,  1., -3.,  0.],
       [ 1.,  1., -1., ...,  0., -1.,  1.],
       [ 1.,  0.,  2., ...,  0., -1.,  0.],
       ...,
       [ 1.,  0.,  0., ..., -1.,  0.,  0.],
       [ 0.,  0.,  1., ..., -2.,  2., -2.],
       [ 0.,  1., -1., ..., -2.,  0., -1.]], shape=(60, 39))

In [118]:

numpy.diff(data, axis =0) 
#by columns.

array([[ 0.,  1.,  1., ..., -2.,  0.,  1.],
       [ 0.,  0., -1., ...,  1.,  1.,  0.],
       [ 0., -1.,  1., ...,  1.,  1.,  0.],
       ...,
       [ 0.,  0.,  0., ..., -1.,  0.,  0.],
       [ 0., -1., -1., ..., -1.,  1., -1.],
       [ 0.,  0.,  1., ...,  1., -1.,  0.]], shape=(59, 40))

In [119]:
numpy.max(numpy.diff(data, axis=1), axis=1)

array([ 7., 12., 11., 10., 11., 13., 10.,  8., 10., 10.,  7.,  7., 13.,
        7., 10., 10.,  8., 10.,  9., 10., 13.,  7., 12.,  9., 12., 11.,
       10., 10.,  7., 10., 11., 10.,  8., 11., 12., 10.,  9., 10., 13.,
       10.,  7.,  7., 10., 13., 12.,  8.,  8., 10., 10.,  9.,  8., 13.,
       10.,  7., 10.,  8., 12., 10.,  7., 12.])

In [120]:
numpy.max(numpy.absolute(numpy.diff(data, axis=1)), axis=1)

array([12., 14., 11., 13., 11., 13., 10., 12., 10., 10., 10., 12., 13.,
       10., 11., 10., 12., 13.,  9., 10., 13.,  9., 12.,  9., 12., 11.,
       10., 13.,  9., 13., 11., 11.,  8., 11., 12., 13.,  9., 10., 13.,
       11., 11., 13., 11., 13., 13., 10.,  9., 10., 10.,  9.,  9., 13.,
       10.,  9., 10., 11., 13., 10., 10., 12.])